#!/bin/ksh --login
#
#BSUB -oo /gpfs/dell2/emc/verification/save/Geoffrey.Manikin/meteograms.nam/cloud06.out
#BSUB -eo /gpfs/dell2/emc/verification/save/Geoffrey.Manikin/meteograms.nam/cloud06.out 
#BSUB -J cloud06 
#BSUB -n 32 
#BSUB -R span[ptile=1]
#BSUB -W 00:45
#BSUB -cwd /gpfs/dell1/stmp/Geoffrey.Manikin
#BSUB -q "dev"
#BSUB -R "affinity[core]"
#BSUB -P NAM-T2O
#BSUB -x

set -x

export HOLDIN=/gpfs/dell1/stmp/Geoffrey.Manikin
export GBexec=/nwprod/util/exec

cyc=`cut -c 15-16 /gpfs/dell1/nco/ops/com/date/t06z`
ymd=`cut -c 7-14 /gpfs/dell1/nco/ops/com/date/t06z`
export cyc

if [ ! -s /gpfs/dell1/nco/ops/com/nam/prod/nam.${ymd}/nam_${ymd}${cyc}.snd.tm00 ]
then
  sleep 600 
fi

rm -rf $HOLDIN/cloud*nam
mkdir -p $HOLDIN/cloudgrams.nam
mkdir -p $HOLDIN/cloudgrams.nam/hold
###rm poescript
set +x
set -x

cp /gpfs/dell1/nco/ops/com/date/t06z /gpfs/dell2/emc/verification/save/Geoffrey.Manikin/meteograms.nam/CLOUDDATE
cd $HOLDIN/cloudgrams.nam

set +x

rm poescript

split="1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32"
for unit in $split
do

echo $unit
mkdir -p $HOLDIN/cloudgrams.nam/cloud${unit}
echo "/gpfs/dell2/emc/verification/save/Geoffrey.Manikin/meteograms.nam/run_cloud_new ${unit} ${cyc} 0-84" >> poescript
done

chmod 775 poescript
export MP_PGMMODEL=mpmd
export MP_CMDFILE=poescript
#
# Execute the script.

echo beforelsf
mpirun -l cfp poescript
echo pastlsf

bsub < /gpfs/dell2/emc/verification/save/Geoffrey.Manikin/meteograms.nam/run_ftp_cloud
exit
