#!/bin/sh
echo 'into'

piece=$1
cyc=$2
ver=$3
sleep_num=`expr ${piece} \* 2`
#sleep $sleep_num

da00=`cut -c 7-14  /lfs/h1/ops/prod/com/date/t${cyc}z`
hr00=`cut -c 7-14  /lfs/h1/ops/prod/com/date/t${cyc}z`

if [ ! -s /gpfs/dell1/stmp/Geoffrey.Manikin/meteograms.nam/meteogram${piece} ]
then
  echo exiting
  exit
fi
cd /lfs/h2/emc/stmp/geoffrey.manikin/meteograms.nam/meteogram${piece}
cp /lfs/h2/emc/vpppg/save/geoffrey.manikin/meteograms.nam/coltbl.xwp .

    cat << EOF > $$.pack 
PMSL       900.       1090.      .1    .01
P01I         0.         20.      .01    1.
C01I         0.         20.      .01    1.
UWND       -70.         70.      .1     1.
VWND       -70.         70.      .1     1. 
TMPC      -100.         50.      .1     1.
HLCY    -10000.       4000.      .1     1.
CDBP         0.       1100.      1.     .01
VSBY         0.         50.      .1     .001
WSYM         0.     512000.      1.     1.
DWPC      -100.         35.      .1     1.
EOF


file_name=input_list_${piece}
cp /lfs/h2/emc/vpppg/save/geoffrey.manikin/meteograms.nam/$file_name /lfs/h2/emc/stmp/Geoffrey.Manikin/meteograms.nam/meteogram${piece}/$file_name 

nlines=`cat $file_name | wc -l`
line=0

fmdl1=/lfs/h1/ops/prod/com/nam/${ver}/nam.${da00}/nam_${da00}${hr00}.sfc.tm00
cp /lfs/h1/ops/prod/com/nam/${ver}/nam.${da00}/nam_${da00}${hr00}.sfc_aux.tm00 fmdl2
fmdl3=/lfs/h1/ops/prod/com/nam/${ver}/nam.${da00}/nam_${da00}${hr00}.snd.tm00

while [ $line -lt $nlines ]
do 
  line=`expr $line + 1`    
  stn=`awk 'NR==j{print $0}' j=$line $file_name`

stnm=`echo $stn | cut -c1-6`
stid=`echo $stn | cut -c8-34`
echo $stnm
echo $stid

if test "$stnm" = "done"
then
/bin/rm $$.pack
gpend

mv *gif /lfs/h2/emc/stmp/Geoffrey.Manikin/meteograms.nam/hold/.
exit
fi

    sfcfil << EOF > /dev/null
SFOUTF   = $$.sfc
SFPRMF   = $$.pack
STNFIL   = sfstns.tbl
SHIPFL   = NO
TIMSTN   = 200/2
r

ex
EOF

    sflist << EOF > /dev/null
SFFILE  = $fmdl1
AREA    = @$stnm
DATTIM  = all
SFPARM  = pmsl;p01m/25.399;c01m/25.399;uwnd;vwnd;t2ms
OUTPUT  = f/$$.list01
IDNTYP  = STNM
r

ex
EOF

vi $$.list01 << EOF > /dev/null
:1,\$ s/T2MS/TMPC/g
:1,\$ s/P01M/P01I/g
:1,\$ s/C01M/C01I/g
:wq
EOF


    sflist << EOF > /dev/null
SFFILE  = fmdl2
AREA    = @$stnm
DATTIM  = all
SFPARM  = hlcy;cdbp;vsbk*0.62137;wsym;td2m
OUTPUT  = f/$$.list02
IDNTYP  = STNM
r

ex
EOF

vi $$.list02 << EOF > /dev/null
:1,\$ s/TD2M/DWPC/g
:1,\$ s/VSBK/VSBY/g
:wq
EOF

edfiles="$$.list01 $$.list02"
for file in $edfiles; do
	sfedit << EOF > /dev/null
sfefil=$file
sffile=$$.sfc
r

ex
EOF
/bin/rm $file
done

mv $$.sfc gotit.sfc

sfgram << EOF > /dev/null
\$respond=yes
SFFILE	= gotit.sfc
DATTIM	= all
STATION = @$stnm
TRACE1  = tmpf:1:5;dwpf:2:5/2;3/ /TIC
NTRACE	= 1
TAXIS	= 
BORDER	= 1//2
MARKER	= 0
TITLE	= 1/+3/$stnm  NAM 12 KM 60 LYR FCST 2-M TEMP (RED) DEWPOINT (GREEN)
CLEAR	= yes
DEVICE  = GIF|${stnm}.meteogram.gif | 900;800
PANEL	= 0;0.65;1;1 
TEXT	= medium/22/2////HW 
r

ex
EOF

sfgram << EOF > /dev/null
TRACE1  = p01i:1:5;c01i:2:5/24;16/0;0.50;0.25/0.10;0.25!;brbk:1:2;wsym:2:3/28;23
CLEAR   = no
PANEL   = 0;0.49;1;0.84
TITLE   = 1/-6/TOTAL PCP (BLUE) CONV PCP (ORANGE-DASHED) WEATHER (PURPLE) WIND
r

ex
EOF

sfgram << EOF > /dev/null
TRACE1  = pmsl:1:5/17//TIC!hlcy:2:5/26
PANEL   = 0;0.30;1;0.65
TITLE   = 1/-6/SEA LEVEL PRESSURE (ORANGE) HELICITY (BLUE-DASHED)
r

ex
EOF

sfgram << EOF > /dev/null
TRACE1  = vsby:1:5/15/-1;14/;1;2;3;5!cdbp:2:5/29/1050;50;-200
PANEL   = 0;0.11;1;0.46
TITLE   = 1/-6/ VISIBILITY (miles) (RED)    CLOUD BASE PRESSURE (PURPLE)
r

ex
EOF

sntser << EOF2 > /dev/null 
SNFILE	= $fmdl3 
CLEAR	= no 
PANEL	= 0;0;1;.21
TITLE	= 1/0/$stnm $stid  NAM CAPE (BROWN) CINS (BLUE-DASHED)
DATTIM	= all
LEVELS  = 0
SNPARM  =
VCOORD  = PRES
STNDEX  = CAPE
AREA    = @$stnm
PTYPE   = lin
YAXIS   = -100/3600/1000
BORDER   = 1//2
LINE     = 16/1/5
MARKER   = 0
r

TITLE	= 
STNDEX  = CINS*-1
LINE     = 24/2/4
r

ex
EOF2
/bin/rm gotit.sfc

gpend
done

exit
