#!/bin/bash
#
#PBS -N meteo00
#PBS -o /lfs/h2/emc/vpppg/save/geoffrey.manikin/meteograms.nam/meteo00.out
#PBS -e /lfs/h2/emc/vpppg/save/geoffrey.manikin/meteograms.nam/meteo00.err
#PBS -l select=2:ncpus=16:mpiprocs=4:mem=200GB
#PBS -q dev
#PBS -l walltime=01:00:00
#PBS -A VERF-DEV

set +x

source /u/geoffrey.manikin/.bashrc
source /lfs/h2/emc/vpppg/save/geoffrey.manikin/versions/run.ver
echo $envvar_ver
module load envvar/${envvar_ver}
module load PrgEnv-intel/${PrgEnv-intel_ver}
module load intel/${intel_ver}module load craype/${craype_ver}
module load cray-mpich/${craympich_ver}
module load cfp/${cfp_ver}
module load wgrib2/${wgrib2_ver}
module load gempak/${gempak_ver}
echo 'here'
module load cray-libsci

export HOLDIN=/lfs/h2/emc/stmp/geoffrey.manikin

cyc=`cut -c 15-16 /lfs/h1/ops/prod/com/date/t00z`
ymd=`cut -c 7-14 /lfs/h1/ops/prod/com/date/t00z`
version=v4.2
export cyc

if [ ! -s /lfs/h1/ops/prod/com/nam/${version}/nam.${ymd}/nam_${ymd}${cyc}.sfc.tm00 ]
then
  sleep 600
fi

rm -rf $HOLDIN/meteo*nam
mkdir -p $HOLDIN/meteograms.nam
mkdir -p $HOLDIN/meteograms.nam/hold
set +x
set -x

cp /lfs/h1/ops/prod/com/date/t00z /lfs/h2/emc/vpppg/save/geoffrey.manikin/meteograms.nam/METEODATE
cd $HOLDIN/meteograms.nam

set +x

rm poescript

split="1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32"
for unit in $split
do

echo $unit
mkdir -p $HOLDIN/meteograms.nam/meteogram${unit}
echo "/lfs/h2/emc/vpppg/save/geoffrey.manikin/meteograms.nam/run_mgm_new ${unit} ${cyc} ${version}" >> poescript
done

chmod 775 poescript
#
# Execute the script.

echo beforelsf
mpiexec hostname > hostname.out
#mpirun -l cfp poescript
mpiexec -np 4 --cpu-bind core --depth=2 cfp poescript > poe_out.txt
echo pastlsf

qsub < /lfs/h2/emc/vpppg/save/geoffrey.manikin/meteograms.nam/run_ftp_meteo
exit

